### PR TITLE
Release/2.30.3

### PR DESCRIPTION
**Pull request by DavidCADanneels**
#Fix ClassCastException in OntrackMultiChoiceParameter (when there is only one checkbox a single Boolean is returned iso a JSONArray of Booleans)

### CODE REVIEW

**Comment by dcoraboeuf** [comment]
Can you change the title of this PR? Using a summary of what it's supposed to change/improve?

**Review by dcoraboeuf — COMMENTED** [review]
Why some changes on `OntrackTriggerTest`? I don't see any relationship with the correction brought by the PR.

**Comment by DavidCADanneels** [comment]
The refactoring of the OntrackTriggerTest was done by you on the 2.31 branch (throw ANTLExceptions instead of catching them). I have ported back these change to the 2.30 branch (some time ago already)

**Comment by DavidCADanneels** [comment]
FYI: I was not able to test this locally (yet), the issue did not occur locally.

**Comment by DavidCADanneels** [comment]
I will rework it and test it locally.

**Pull request closed without merging**
